# This workflows starts scraping Routescanner and MSC each day at 06:00 UTC,
# using the v1 scrapers, and opens a PR to merge the gathered data.

name: Scrape Maersk daily
on:
  # Disabled because Routescanner v1 is broken, and MSC v1 is redundant (replaced by v2)
  schedule:
    - cron: '0 6 * * *'
  push:
    paths:
     - ".github/workflows/daily_run.yml"
     #- "webscrapers/routescanner_automated.py"
     #- "webscrapers/msc_automated.py"
     - "webscrapers/maersk.py"
  workflow_dispatch:

jobs:
  maersk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: pip install -U pip wheel setuptools
    - run: pip install -U selenium beautifulsoup4 pandas numpy packaging webdriver-manager
    - run: python maersk.py
      working-directory: ./webscrapers
    - uses: peter-evans/create-pull-request@v5
      with:
        base: "data_staging"
        branch: "maersk-data"
        branch-suffix: "timestamp"
        title: "Add Maersk data"
