# This workflows starts scraping Routescanner each day at 06:00 UTC, and opens a PR to merge the gathered data

name: Scrape routescanner
on:
  schedule:
    - cron: '0 6 * * *'
  push:
    paths:
     - ".github/workflows/routescanner_daily.yml"
     - "routescanner_automated.py"
  workflow_dispatch:

jobs:
  routescanner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: nanasess/setup-chromedriver@v1
    - run: pip install -U pip wheel setuptools
    - run: pip install -U selenium beautifulsoup4 pandas numpy
    - run: pip install git+https://github.com/SergeyPirogov/webdriver_manager@master
    - run: python routescanner_automated.py
    - uses: peter-evans/create-pull-request@v4
      with:
        branch: "routescanner-data"
        branch-suffix: "timestamp"
        title: "Add Routescanner data"
